-- Create students table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  class_name text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(full_name, class_name)
);

-- Create index on class_name for faster queries
CREATE INDEX IF NOT EXISTS idx_students_class_name ON public.students(class_name);

-- Insert all 107 students
INSERT INTO public.students (full_name, class_name) VALUES
('Chizaram Charis Maduabuchukwu', 'AMAZING ANGELS'),
('Marial Iseoluwa John', 'AMAZING ANGELS'),
('Angel Udeme Abasi', 'AMAZING ANGELS'),
('Fifooluwa Moradeyo', 'AMAZING ANGELS'),
('Gratitude Adejuiyigbe', 'AMAZING ANGELS'),
('Patrick Anaya Chinaza', 'AMAZING ANGELS'),
('Monioluwa Zuriel Ojekunle', 'AMAZING ANGELS'),
('Kushoro Keon', 'AMAZING ANGELS'),
('Akinbiyi Oreofe', 'AMAZING ANGELS'),
('Agboola Joseph', 'EXPLORERS'),
('Kindle Favor', 'EXPLORERS'),
('John Moses', 'MAGNIFICENT'),
('Etoh Munachi', 'MAGNIFICENT'),
('Eziohuru Daina Chimemerie', 'MAGNIFICENT'),
('Okoye Jason', 'MAGNIFICENT'),
('Akinsola Emmanuel', 'MAGNIFICENT'),
('Akomolade Morolaoluwa', 'MAGNIFICENT'),
('Akindele Emmanuel', 'MAGNIFICENT'),
('Wenegieme Aretha', 'MAGNIFICENT'),
('Olowe Erife', 'MAGNIFICENT'),
('Franklin Jane Temiloluwa', 'MAGNIFICENT'),
('Abubakar Orange-Win', 'DISCOVERERS'),
('Adekunle Ezra', 'DISCOVERERS'),
('Agboola Jedidiah', 'DISCOVERERS'),
('Akinola Oluwasorekunmi', 'DISCOVERERS'),
('Etoh Caleb', 'DISCOVERERS'),
('Hamza Arif', 'DISCOVERERS'),
('Owoosho Michael', 'DISCOVERERS'),
('Adejumo Elizabeth', 'DISCOVERERS'),
('Ikediashi Ugochukwu', 'DISCOVERERS'),
('Oguoidiegwu Adaeze', 'DISCOVERERS'),
('Omilola Chloe', 'DISCOVERERS'),
('Otitoloju Oluwadamipe', 'DISCOVERERS'),
('Umoetuk Uwanabasi', 'DISCOVERERS'),
('Jan Franklin', 'NOBLE'),
('Oladunmade Durojaiye', 'NOBLE'),
('Anne Akindele', 'NOBLE'),
('Morike Adeniyi', 'NOBLE'),
('Tiffany Atohengbe', 'NOBLE'),
('Oki Fajano', 'NOBLE'),
('Modade Bakare', 'NOBLE'),
('Melchizedek akinola', 'NOBLE'),
('Aviation Mogoli', 'YEAR 1'),
('Uzoamaka Ikediashi', 'YEAR 1'),
('Liam Scott', 'YEAR 1'),
('Joy Agboola', 'YEAR 1'),
('Kayito Okpara', 'YEAR 1'),
('Melvin Nzete', 'YEAR 1'),
('Nisimi Akinbyi', 'YEAR 1'),
('Asher Aderemi', 'YEAR 1'),
('Feivel Wenegieme Franklin', 'YEAR 1'),
('Mary Godonu', 'YEAR 1'),
('Adeniyi Morife', 'YEAR 2'),
('Adike Nonso', 'YEAR 2'),
('Agboola John', 'YEAR 2'),
('Anyanwu Chimdimdu', 'YEAR 2'),
('Charles Adesuwa', 'YEAR 2'),
('Chukwuebuka Chiamaka', 'YEAR 2'),
('Eziohuru Kosiso', 'YEAR 2'),
('Omega Aurelia', 'YEAR 2'),
('Okpala Kaisochukwu', 'YEAR 2'),
('Okonkwo Chiamaka', 'YEAR 2'),
('Olokun Imran', 'YEAR 2'),
('Onabadejo Titoluwanimi', 'YEAR 2'),
('Oyeyemi Ayomiposi', 'YEAR 2'),
('Udeh Akwaugo', 'YEAR 2'),
('Adekunle Adriel', 'YEAR 3'),
('Aderemi David', 'YEAR 3'),
('Muhammad Abdul-Baasit', 'YEAR 3'),
('Bakare Murewa', 'YEAR 3'),
('Olowe Korinayo', 'YEAR 3'),
('Wenegieme Benjamin Franklin', 'YEAR 3'),
('James Jedidiah', 'YEAR 3'),
('Desalu Oluwatobiloba', 'YEAR 3'),
('Owate Oreofeoluwa', 'YEAR 3'),
('Leonard Charles', 'YEAR 3'),
('Raheem Inioluwa', 'YEAR 3'),
('Akimbiyi  Dunsimi', 'YEAR 3'),
('Mogoli Zion', 'YEAR 4'),
('Okonkwo Chizaram', 'YEAR 4'),
('Falobi Victoria', 'YEAR 4'),
('Ikediashi Olisaemeka', 'YEAR 4'),
('Popoola Oyindamola', 'YEAR 4'),
('Kareem Muqsit', 'YEAR 4'),
('Moradeyo Omolayo', 'YEAR 4'),
('Adike Caleb', 'YEAR 4'),
('Owate Inioluwa', 'YEAR 4'),
('Udeh Munachimso', 'YEAR 4'),
('Eiluorir Osiejiele', 'YEAR 4'),
('Eziohuru Chikanyima', 'YEAR 4'),
('Adebule Amelia', 'YEAR 5'),
('Adekoya Oluwatosin', 'YEAR 5'),
('Afolabi Tantoluwa', 'YEAR 5'),
('Deinbo Sobura', 'YEAR 5'),
('Hamza Faisal', 'YEAR 5'),
('Mogoli Salem', 'YEAR 5'),
('Monye Chizaram', 'YEAR 5'),
('Muhammad Muheeb', 'YEAR 5'),
('Odusote Aramide', 'YEAR 5'),
('Oyeyemi Olamiposi', 'YEAR 5'),
('Raheem Rahman', 'YEAR 5'),
('Moradeyo Marayomigba', 'YEAR 5'),
('Okonkwo Kamsi', 'YEAR 6'),
('Onabadejo Tomiloba', 'YEAR 6'),
('Odusote Araoluwa', 'YEAR 6'),
('Adewale Sapphire', 'YEAR 6'),
('Kosoko Armani', 'YEAR 6')
ON CONFLICT DO NOTHING;

-- Verify the import
SELECT COUNT(*) as total_students, COUNT(DISTINCT class_name) as total_classes FROM public.students;
